// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1Hw2CHGS44pXnpcMz4wN6XctAa9uSrv4',
    appId: '1:606035660571:web:c7d34d25e224d506084dbe',
    messagingSenderId: '606035660571',
    projectId: 'frovy-app',
    authDomain: 'frovy-app.firebaseapp.com',
    storageBucket: 'frovy-app.firebasestorage.app',
    measurementId: 'G-6XHGLWZ4FX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE9W44OR2_MMJ77gybAZ4bEKawP865aFU',
    appId: '1:606035660571:android:db902f348d93edc9084dbe',
    messagingSenderId: '606035660571',
    projectId: 'frovy-app',
    storageBucket: 'frovy-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUf5qU5rCgj7bWVoicTaNFB6LYQgRYdnc',
    appId: '1:606035660571:ios:af52cdfddcc9eb9b084dbe',
    messagingSenderId: '606035660571',
    projectId: 'frovy-app',
    storageBucket: 'frovy-app.firebasestorage.app',
    iosBundleId: 'com.example.frovyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUf5qU5rCgj7bWVoicTaNFB6LYQgRYdnc',
    appId: '1:606035660571:ios:af52cdfddcc9eb9b084dbe',
    messagingSenderId: '606035660571',
    projectId: 'frovy-app',
    storageBucket: 'frovy-app.firebasestorage.app',
    iosBundleId: 'com.example.frovyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1Hw2CHGS44pXnpcMz4wN6XctAa9uSrv4',
    appId: '1:606035660571:web:c7d6c37b7b527bfb084dbe',
    messagingSenderId: '606035660571',
    projectId: 'frovy-app',
    authDomain: 'frovy-app.firebaseapp.com',
    storageBucket: 'frovy-app.firebasestorage.app',
    measurementId: 'G-W4MG7YM4Z5',
  );

}