// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDrcIlZ-rY7-Cn0YI4LqRTwLT2KiEx0co',
    appId: '1:1014519853798:web:04579a46bc090469d38127',
    messagingSenderId: '1014519853798',
    projectId: 'fro-vy',
    authDomain: 'fro-vy.firebaseapp.com',
    storageBucket: 'fro-vy.firebasestorage.app',
    measurementId: 'G-EVE61MT6Y5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmhBf_Zt6y6-Wu7FVg1iYP50QUBVGxu0o',
    appId: '1:1014519853798:android:21139fd1a2b07265d38127',
    messagingSenderId: '1014519853798',
    projectId: 'fro-vy',
    storageBucket: 'fro-vy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF6sED2NE4KE29zoaSN1o9ezx_pZlGWQk',
    appId: '1:1014519853798:ios:ad53909d3890f574d38127',
    messagingSenderId: '1014519853798',
    projectId: 'fro-vy',
    storageBucket: 'fro-vy.firebasestorage.app',
    androidClientId: '1014519853798-fdkn056dr9qbrn768esqdij3t6ugps9f.apps.googleusercontent.com',
    iosClientId: '1014519853798-q9b2d37sej8t0p97nvpvgteql14ja04j.apps.googleusercontent.com',
    iosBundleId: 'com.example.frovyOutputTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCF6sED2NE4KE29zoaSN1o9ezx_pZlGWQk',
    appId: '1:1014519853798:ios:ad53909d3890f574d38127',
    messagingSenderId: '1014519853798',
    projectId: 'fro-vy',
    storageBucket: 'fro-vy.firebasestorage.app',
    androidClientId: '1014519853798-fdkn056dr9qbrn768esqdij3t6ugps9f.apps.googleusercontent.com',
    iosClientId: '1014519853798-q9b2d37sej8t0p97nvpvgteql14ja04j.apps.googleusercontent.com',
    iosBundleId: 'com.example.frovyOutputTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDrcIlZ-rY7-Cn0YI4LqRTwLT2KiEx0co',
    appId: '1:1014519853798:web:089f35596a31b528d38127',
    messagingSenderId: '1014519853798',
    projectId: 'fro-vy',
    authDomain: 'fro-vy.firebaseapp.com',
    storageBucket: 'fro-vy.firebasestorage.app',
    measurementId: 'G-L24KYK0T5P',
  );
}
